server:
  port: 8090

spring:
  application:
    name: customer-service

  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      username: alibou
      password: alibou
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
